### ISSUE TITLE
Add simple signal filtering

### ISSUE THREAD

**Issue by dschaeffer17** [uclahedp/dataview#16]
Would be useful to implement simple high/low pass filtering as an option.

**Comment by pheuer** [comment]
A very simple lowpass filter has been implemented in the latest version: let me know what you think. I'm hesitant to include anything more complicated (say, setting frequency bandpasses) because of complexity. a highpass = unfiltered - lowpass option could be added easily. 

For more rigorous filtering options, check out the uclahedp.analyze.filter module. A crude 1D bandpass filter has been implemented, and I plan to do a 2D one.

**Comment by dschaeffer17** [comment]
Thanks Peter.  Could you add that highpass=unfiltered-lowpass option?

**Comment by pheuer** [comment]
Sure, that's easy. I have added it now.
